# Uncomment the next line to define a global platform for your project
platform :ios, '10.2'
use_frameworks!

target 'costPerWear' do
  # Pods for costPerWear

pod 'SnapKit', '~> 4.0.0'
pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
pod 'AWSAuthCore', '~> 2.6.1'
pod 'AWSUserPoolsSignIn', '~> 2.6.1'
pod 'AWSAuthUI', '~> 2.6.1'

#pod 'AWSAutoScaling'
#pod 'AWSCloudWatch'
#pod 'AWSCognito'
#pod 'AWSCore'
#pod 'AWSDynamoDB'
#pod 'AWSEC2'
#pod 'AWSElasticLoadBalancing'
#pod 'AWSKinesis'
#pod 'AWSLambda'
#pod 'AWSMachineLearning'
#pod 'AWSMobileAnalytics'
#pod 'AWSS3'
#pod 'AWSSES'
#pod 'AWSSimpleDB'
#pod 'AWSSNS'
#pod 'AWSSQS'
#pod 'AFNetworking'
 
end
